spring:
  application:
    name: event-platform-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/platform-backend
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: geancardosorabelomota@gmail.com
    password: oqky gmeo okfg tuqg
    properties:
      mail:
        smtp:
          auth: true
          enable: true
security:
  secret: a-string-secret-at-least-32-characters