spring:
  application:
    name: event-platform-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/platform-backend
    username: postgres
    password: postgres
security:
  secret: a-string-secret-at-least-32-characters